# Generated by Django 4.1.4 on 2022-12-21 00:06

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False, help_text='Flag to determine if email has been verified')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='The date email was verified', null=True)),
                ('image', models.ImageField(blank=True, help_text='This image will be gotten from the bvn data return', null=True, upload_to=account.models.upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='The date this user account was deleted', null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('verification_completed', models.BooleanField(default=False, help_text='Flag that determined if the user has completed all necessary verifications')),
                ('phone', models.CharField(max_length=20)),
                ('phone_verified', models.BooleanField(default=False, help_text='Flag that determined if the phone number has been verified')),
                ('phone_verified_at', models.DateTimeField(blank=True, help_text='The date phone number was verified', null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorce', 'Divorce')], help_text='The marital status of the user', max_length=10, null=True)),
                ('children', models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two'), ('other', 'Three and above')], max_length=20, null=True)),
                ('resident_type', models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented')], max_length=10, null=True)),
                ('rent_per_year', models.DecimalField(blank=True, decimal_places=2, help_text='This field is required for a rented apartment', max_digits=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lga', models.CharField(blank=True, help_text='Local government area of the user location', max_length=100, null=True)),
                ('educational_status', models.CharField(blank=True, choices=[('graduate', 'Graduate'), ('under_graduate', 'Under graduate'), ('post_graduate', 'Post graduate'), ('high_school', 'High school'), ('other', 'other')], help_text='Educational level of the user', max_length=20, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('unemployed', 'Unemployed'), ('entrepreneur', 'Entrepreneur'), ('employed', 'Employed')], help_text='Employment status of the user', max_length=20, null=True)),
                ('business_name', models.CharField(blank=True, help_text='The employer name or business name of the user working place', max_length=100, null=True)),
                ('monthly_income', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBvn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('marital', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('mixing', models.CharField(max_length=100)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserNextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='The authorization code of the card', max_length=100, null=True)),
                ('type', models.CharField(blank=True, help_text='The type of card used', max_length=100, null=True)),
                ('start', models.IntegerField(blank=True, help_text='First six digit of the card', null=True)),
                ('last', models.IntegerField(blank=True, help_text='First six digit of the card', null=True)),
                ('account_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_reusable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
