# Generated by Django 4.1.4 on 2022-12-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_address_user_address1_user_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='exp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='signature',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
