# Generated by Django 4.1.4 on 2022-12-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='years_at_residence',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='children',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='educational_status',
            field=models.CharField(blank=True, help_text='Educational level of the user', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_status',
            field=models.CharField(blank=True, help_text='Employment status of the user', max_length=20, null=True),
        ),
    ]
